name: Release Docker Image

on:
  workflow_run:
    types:
      - completed
    workflows:
      - Create Release
  release:
    types: [published]

jobs:
  push-docker-image:
    name: Push Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-repository: [juansecu/github-discord-updater]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ matrix.docker-repository }}:${{ github.ref_name }},${{ matrix.docker-repository }}:latest
